//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidAssignment.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectRequest()
        {
            this.FoodDistributions = new HashSet<FoodDistribution>();
        }
    
        public int RequestID { get; set; }
        public int RestaurantID { get; set; }
        public int FoodItemID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Quantity { get; set; }
        public int PreserveTime { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FoodItem FoodItem { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodDistribution> FoodDistributions { get; set; }
    }
}
