//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidAssignment.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDistribution
    {
        public int DistributionID { get; set; }
        public int RequestID { get; set; }
        public int EmployeeID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DistributionDate { get; set; }
    
        public virtual CollectRequest CollectRequest { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
